[platformio]
default_envs = xteink_x3

[env:xteink_x3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_upload.offset_address = 0x10000
board_build.flash_mode = dio
board_build.flash_size = 16MB
board_build.partitions = partitions.csv

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DEINK_DISPLAY_SINGLE_BUFFER_MODE=1
  -DFREEINK_DEVICE_X3=1
  -std=gnu++2a

build_unflags =
  -std=gnu++11

lib_deps =
  BoardConfig=symlink://freeink-sdk/libs/hardware/BoardConfig
  EInkDisplay=symlink://freeink-sdk/libs/display/FreeInkDisplay
  InputManager=symlink://freeink-sdk/libs/hardware/InputManager
  PowerManager=symlink://freeink-sdk/libs/hardware/PowerManager
  SDCardManager=symlink://freeink-sdk/libs/hardware/SDCardManager
  XteinkDetect=symlink://freeink-sdk/libs/hardware/XteinkDetect
  bblanchon/ArduinoJson @ 7.4.2

[env:xteink_x3_release]
extends = env:xteink_x3
build_flags =
  ${env:xteink_x3.build_flags}
  -DUPDATE_SIGN=1
  -DBOOKPET_REQUIRE_SIGNED_UPDATES=1
